### ISSUE TITLE
LogbookClientHttpRequestInterceptor throws IOException in Spring

### ISSUE THREAD

**Issue by dmitry537** [zalando/logbook#1093] opened 2021-07-16 14:54 UTC
When using Spring RestTtemplate and LogbookClientHttpRequestInterceptor, RestTemplate throws IOException
I made a small demo application that demonstrates this:
[https://github.com/dmitry537/logbook-interceptor-demo](https://github.com/dmitry537/logbook-interceptor-demo)

What am I doing wrong?

**Comment by dmitry537** [comment] 2021-07-16 15:05
This seems to be related to https://github.com/zalando/logbook/issues/963

**Comment by whiskeysierra** [comment] 2021-08-17 07:04
Yes, it's a duplicate of #963 and there is a PR in progress #1041

**Closed by whiskeysierra** 2021-08-17 07:04 UTC
