### ISSUE TITLE
LogbookFilter (servlet) is not working due to lack of jakarta.* support

### ISSUE THREAD

**Issue by alexanderseik** [zalando/logbook#1401] opened 2023-02-02 10:27 UTC
HI,

I want to use Logbook for incoming http request logging in my Spring Boot (3.x.x) application.
Incoming request are not logged, client logging is working though.

## Description
There was an upgrade of the servlet api (javax.* to jakarta.*) in Spring Boot.
I think the issue is that Spring Boot registers jakarta.HttpFilter and not javax.HttpFilter anymore.

## Expected Behavior
Request/Response servlet logging works

## Actual Behavior
No logging happens for incoming requests/responses

## Possible Fix
Upgrade dependencies

## Steps to Reproduce
- spring-boot-starter-parent:3.0.2
- logbook-spring-boot-starter:2.14.0
- Enable TRACE logging
- Write a simple controller
- Call the endpoint
- Review the logs

## Context
Prevents using Logbook in newer Spring versions

## Your Environment
spring-boot-starter-parent:3.0.2
logbook-spring-boot-starter:2.14.0

BR
Alexander

**Comment by whiskeysierra** [comment] 2023-02-02 10:29
Duplicate of #1344

**Closed by whiskeysierra** 2023-02-02 10:29 UTC
Labels: Bug
